# Site settings
title: 
header-img: img/home-bg.png
email: chrissygonzalez@gmail.com
copyright_name: chrissygonzalez
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: chrissygonzalez
github_username:  chrissygonzalez
learn_profile: chrissygonzalez
email_username: chrissygonzalez@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
